### ISSUE TITLE
Clarity on rewrites/redirects documentation

### ISSUE THREAD

**Issue by lyzadanger** [netlify/netlify-home#10]
Hi! Minor tweak request:

Currently, https://www.netlify.com/docs/redirects reads in part:

> You can configure redirects and rewrite rules for your Netlify site by adding a `_redirects` file to the root of your site folder.

It would have saved me a build and some time if it had been clearer that it meant my site's _public folder_, not the root level of the repository itself. It was a little unclear from the wording.

Also, it's not documented so I assume there's no comment syntax for that file, correct? It would be nice for me if I could add some comments to my `_redirects_` file so I remembered what I was up to, later. Bonus points!

Cheers!

**Comment by biilmann** [comment]
Thanks, great feedback!

I've updated the docs now to clarify the point about making sure the _redirects file ends up in the site's public folder. Also added comments to the _redirects examples, to show how that's done.

You can use # to comment the _redirects file.
